Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"  # ou outra box Ubuntu 16.04 compatível
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.hostname = "zabbix-server"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048  # Ajuste a memória da VM, se necessário
    vb.cpus = 2       # Ajuste o número de CPUs da VM, se necessário
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    wget https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+xenial_all.deb
    sudo dpkg -i zabbix-release_5.0-1+xenial_all.deb
    sudo apt-get update
    sudo apt-get install -y zabbix-server-mysql zabbix-frontend-php apache2 mysql-server php7.0 libapache2-mod-php7.0 php7.0-mysql

    # Configurar o MySQL
    sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password zabbix'
    sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password zabbix'
    sudo mysql -uroot -pzabbix <<MYSQL_SCRIPT
      CREATE DATABASE zabbix character set utf8 collate utf8_bin;
      GRANT ALL PRIVILEGES ON zabbix.* TO zabbix@localhost IDENTIFIED BY 'zabbix';
      FLUSH PRIVILEGES;
MYSQL_SCRIPT

    # Importar o schema do Zabbix
    sudo zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | sudo mysql -uzabbix -pzabbix zabbix

    # Configurar o PHP
    sudo sed -i 's/;date.timezone =/date.timezone = America\/Sao_Paulo/' /etc/php/7.0/apache2/php.ini
    sudo systemctl restart apache2

    # Configurar o timezone
    sudo timedatectl set-timezone America/Sao_Paulo
  SHELL
end
