Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "10240"
    vb.cpus = 4
  end
  config.vm.network "public_network", ip: "192.168.1.121", bridge: "wlp3s0"
  config.vm.synced_folder ".", "/vagrant", SharedFoldersEnableSymlinksCreate: false
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y git
  SHELL
end

