# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/centos-stream-9"

  # Configuração de rede privada (comentada para desativar)
  # config.vm.network "private_network", ip: "192.168.33.14"

  # Configuração de rede pública usando uma interface específica com DHCP
  config.vm.network "public_network", bridge: "wlp3s0", use_dhcp_assigned_default_route: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
config.vm.provision "shell", inline: <<-SHELL
  yum install httpd wget unzip vim -y
  sudo systemctl start httpd
  sudo systemctl enabled httpd
  sudo mkdir -p /tmp/finance
  sudo cd /tmp/finance
  sudo wget https://www.tooplate.com/zip-templates/2135_mini_finance.zip
  sudo unzip -o 2135_mini_finance.zip
  sudo cp -r 2135_mini_finance/* /var/www/html
  sudo systemctl restart httpd
  sudo cd /tmp/
  sudo rm -rf /tmp/finance
  SHELL
end
