Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "app01"
    config.vm.network "public_network", ip: "192.168.1.101", bridge: "wlp3s0"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.provision "shell", path: "provision.sh"
end