apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment  
  namespace: giropops
  labels:
    app: nginx-deployment
    fruta: banana
spec:
  replicas: 14
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.17.0
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.3"
            memory: "64Mi"

