apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropopos
  name: giropopos
spec:
  containers:
  - image: nginx
    name: giropopos
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
