version: '3.7'

services:
  mysql-server:
    image: mysql
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "&l4E?K6q9Y69"
      MYSQL_ROOT_PASSWORD: "&l4E?K6q9Y69"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--default-authentication-plugin=mysql_native_password"
    ]
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zabbix-network

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway
    container_name: zabbix-java-gateway
    restart: unless-stopped
    networks:
      - zabbix-network

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server-mysql
    environment:
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "&l4E?K6q9Y69"
      MYSQL_ROOT_PASSWORD: "&l4E?K6q9Y69"
      ZBX_JAVAGATEWAY: "zabbix-java-gateway"
    ports:
      - "10051:10051"
    restart: unless-stopped
    depends_on:
      - mysql-server
      - zabbix-java-gateway
    networks:
      - zabbix-network

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web-nginx-mysql
    environment:
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "&l4E?K6q9Y69"
      MYSQL_ROOT_PASSWORD: "&l4E?K6q9Y69"
    ports:
      - "80:8080"
    restart: unless-stopped
    depends_on:
      - mysql-server
      - zabbix-server-mysql
    networks:
      - zabbix-network

  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: "zabbix-server-mysql"
    depends_on:
      - zabbix-server-mysql
    networks:
      - zabbix-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    networks:
      - zabbix-network
    depends_on:
      - mysql-server
      - zabbix-server-mysql
      - zabbix-web-nginx-mysql

networks:
  zabbix-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local