name: CI-CD

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o codigo
        uses: actions/checkout@v4

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construção e envio da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            leandrojustino/devops4dev-review:v${{ github.run_number}}
            leandrojustino/devops4dev-review:latest
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Passo 01
        run: echo "Execução do Deploy"
