Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder "./ansible", "/ansible"
  
  # Configuração da rede para usar a interface wlp3s0 e obter um endereço IP via DHCP
  config.vm.network "public_network", bridge: "wlp3s0", type: "dhcp"
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y ansible
    ansible-playbook --connection=local /ansible/playbook.yaml
  SHELL
end

