# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/centos-stream-9"

  # Configuração de rede privada (comentada para desativar)
  # config.vm.network "private_network", ip: "192.168.33.14"

  # Configuração de rede pública usando uma interface específica
  config.vm.network "public_network", bridge: "wlp3s0"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
