# Use a imagem base do Nginx
FROM nginx:latest

# Copie o arquivo index.html para o diretório padrão do Nginx
COPY index.html /usr/share/nginx/html/index.html

# Exponha a porta 80 para o Nginx
EXPOSE 80

